function DrawHelp()
print("certtool.lua [action] [args]")
print()
print("certtool.lua list <path>                                     - list certificates in file at <path>")
print("certtool.lua show <path>                                     - show details of certificates in file at <path>")
print("certtool.lua bundle <path 1> ... <path n> -out <outpath>     - bundle certificates listed into a single filei at 'outpath'")
print("certtool.lua unbundle <path>                                 - unbundle certificates out of a single file into a file per certificate")
print("certtool.lua scrape <hostname>:<port>                        - connect to host and print/check certificates it offers")
print("certtool.lua pem2pfx <cert> <key>                            - convert pem certificate and key files to a single pfx file")
print("certtool.lua pfx2pem <path>                                  - unpack pfx file at <path> into pem certificate and key files")
print("certtool.lua ca  <name> <certificate args>                   - create a certificate authority called <name> (if name is ommited ask for fields)")
print("certtool.lua csr <name> <certificate args>                   - create a signing request for a certificate with common-name <name> (if name is ommited ask for fields)")
print("certtool.lua cert <name> <certificate args>                  - create a certificate with common-name <name> (if name is ommited ask for fields)")
print("certtool.lua key <path>                                      - create public key at <path>")
print("certtool.lua revoke <path> -ca <ca name>                     - revoke certificate in file at <path> that was created by C.A. <ca name>")
print("certtool.lua crl -ca <ca name> -o <path>                     - create a certificate revocation list at <path> for C.A. <ca name>")
print("certtool.lua enc <path> <options>                            - encrypt file at <path> with a password")
print("certtool.lua dec <path> <options>                            - decrypt file at <path> with a password")
print("certool.lua zerossl:cert <name> <options>                    - create certificate using zerossl")
print("certool.lua zerossl:list                                     - list zerossl certificates")
print("certool.lua zerossl:show <id>                                - show details of certificate with hash id <id>")
print("certool.lua zerossl:info <id>                                - show details of certificate with hash id <id>")
print("certool.lua zerossl:valid <id>                               - validate a certificate with hash id <id> using 'file' method")
print("certool.lua zerossl:email <id> -email <dest.email>           - validate certificate with hash id <id> by sending email to 'dest.email'")
print("certool.lua zerossl:install <id>                             - install certificate with hash id <id>")
print("certool.lua zerossl:get <id>                                 - get (download) certificate with hash id <id>")
print("certool.lua zerossl:cancel <id>                              - cancel certificate with hash id <id>")
print("certool.lua zerossl:revoke <id>                              - revoke certificate with hash id <id>")
print("certool.lua zerossl:provision                                - create, validate and install a new certificate")
print("certtool.lua --help                                          - this help")
print("certtool.lua -help                                           - this help")
print("certtool.lua -?                                              - this help")
print()
print("when creating certificates, the path to an alternative working directory can be provided with '-dir <path>'. The working directory contains both certificate authorities and certificates produced with them, each stored in it's own directory.");
print()
print("revoking certificates is a two-step process. First you revoke the certificate in a C.A.'s database, then you produce a Certificate Revocation List (CRL) of all revoked certificates for a C.A. that you can supply to programs to inform them of revoked certificates.");
print()
print("The zerossl: commands are somewhat experimental. You must supply your API key using either the -api command-line argument, or by setting an environment variable 'ZEROSSL_API_KEY'. Validation using email has been seen to work, other validation methods are untested")
print()
print("OPTIONS")
print(" -bits <n>                   bitwidth of certificate key, defaults to 2048")
print(" -days <n>                   days that certificate will be valid for")
print(" -org  <org name>            organization name")
print(" -location  <location>       location")
print(" -loc  <location>            location")
print(" -country <2-letter code>    2-letter country code")
print(" -cc <2-letter code>         2-letter country code")
print(" -email <address>            certificate email, or email to send validations to (zerossl)")
print(" -ca <C.A. name>             name of certificate authority to use")
print(" -copy                       copy details from certificate of signing C.A.")
print(" -api <key>                  supply api key for commands (currently zerossl commands) requiring it")
print(" -out <path>                 output path for encrypt, decrypt and zerossl:get commands")
print(" -o <path>                   output path for encrypt, decrypt and zerossl:get commands")
print(" -algo <algorithm>           encryption algorithm to use for encrypt/decrypt command (defaults to aes-256-cbc)")
print(" -hash <algorithm>           hashing/digest algorithm to use for encrypt/decrypt command (defaults to sha256)")
print(" -digest <algorithm>         hashing/digest algorithm to use for encrypt/decrypt command (defaults to sha256)")
print()
print("<certificate args> are a set of arguments describing the fields within a certificate, signing request or C.A. If none are specified, and no <name> argument is specified then an interactive query mode will be activated to ask for values. The only field that must have a value is 'name'. If interactive query mode is not desired then arguments can be specified on the command-line using:")
print()
print(" -bits <n>                   bitwidth of certificate key, defaults to 2048")
print(" -days <n>                   days that certificate will be valid for")
print(" -org  <org name>            organization name")
print(" -location  <location>       location")
print(" -loc  <location>            location")
print(" -country <2-letter code>    2-letter country code")
print(" -cc <2-letter code>         2-letter country code")
print(" -email <address>            contact email address")
print(" -ca <C.A. name>             name of certificate authority to use")
print(" -copy                       copy details from certificate of signing C.A.")
print()
print("The 'enc' and 'dec' commands accept the following options/arguments:")
print()
print(" -out <path>          path to encrypted/decrypted output file. Without this certtool.lua will produce output filenames by appending '.enc' to encrypted files and '.dec'. to decrypted files")
print(" -o <path>            path to encrypted/decrypted output file. Without this certtool.lua will produce output filenames by appending '.enc' to encrypted files and '.dec'. to decrypted files")
print(" -algo <algorithm>    encryption algorithm to use (defaults to aes-256-cbc)")
print(" -hash <algorithm>    hashing/digest algorithm to use (defaults to sha256)")
print(" -digest <algorithm>  hashing/digest algorithm to use (defaults to sha256)")
print()
print("")
print("Examples:")
print()
print("Show certificate details")
print("  certtool.lua show ./server.crt")
print("Connect to service and output its certificate list")
print("  certtool.lua scrape myserver:443")
print("Bundle certificates into cert_bundle.pem")
print("  certtool.lua bundle -out cert_bundle.pem cert1.pem cert2.pem cert3.pem")
print("Unbundle certificates from cert_bundle.pem into seperate files")
print("  certtool.lua unbundle cert_bundle.pem")
print("Create a certificate authority in interactive mode (asks for needed info)")
print("  certtool.lua ca")
print("Create a certificate authority called 'myCA' with org and email fields set")
print("  certtool.lua ca myCA -org 'My Company' -email webmaster@my.com")
print("Create a certificate signing request in interactive mode")
print("  certtool.lua csr")
print("Create a certificate signing request (to be signed by another CA) for a certificate called 'server_cert'")
print("  certtool.lua csr server_cert")
print("Create a certificate in interactive mode")
print("  certtool.lua cert")
print("Create a certificate called 'server_cert' using C.A. 'myCA'")
print("  certtool.lua cert server_cert -ca myCA")
print("Pack key and certificate into pfx/pkcs12 file")
print("  certtool.lua pem2pfx server_cert.pfx server_cert.crt server_cert.key")
print("Unpack key and certificate from pfx/pkcs12 file")
print("  certtool.lua pfx2pem ./server_cert.pfx")

end

